apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-gateway
data:
  gatewayImage: bsideup/liiklus:0.10.0-rc1
  provisionerImage: ko://github.com/projectriff/riff/kafka-provisioner/cmd/provisioner

