name: CI

on:
  push:
    branches:
    - '**'
    - '!dependabot/**'
  pull_request: {}

jobs:

  unit:
    name: Unit test
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13'
    # TODO remove after https://github.com/actions/setup-go/issues/14
    - name: Add GOPATH/bin to PATH
      run: |
        echo "##[set-env name=GOPATH;]$(go env GOPATH)"
        echo "##[add-path]$(go env GOPATH)/bin"
      shell: bash
    - uses: actions/setup-java@v1
      with:
        java-version: '8.x'

    - name: Test cli
      run: make build coverage verify-docs
      working-directory: cli
    - name: Test dev-utils
      run: |
        echo "TODO"
      working-directory: dev-utils
      if: success() && matrix.os == 'ubuntu-latest'
    - name: Test kafka-provisioner
      run: make build test
      working-directory: kafka-provisioner
      if: success() && matrix.os == 'ubuntu-latest'
    - name: Test nop-provisioner
      run: make build test
      working-directory: nop-provisioner
      if: success() && matrix.os == 'ubuntu-latest'
    - name: Test pulsar-provisioner
      run: make build test
      working-directory: pulsar-provisioner
      if: success() && matrix.os == 'ubuntu-latest'
    - name: Test stream-client-go
      run: |
        set -o errexit
        set -o pipefail
        
        docker run --name liiklus \
          --rm --detach \
          -p 6565:6565/tcp \
          -e storage_positions_type=MEMORY \
          -e storage_records_type=MEMORY \
          sbawaska/liiklus:20200223160346-a85402e4332c51d9
        make test
        docker stop liiklus
      working-directory: stream-client-go
      if: success() && matrix.os == 'ubuntu-latest'
    - name: Test streaming-processor
      run: ./mvnw -q -B -V test
      working-directory: streaming-processor
      shell: bash
      if: success() && matrix.os == 'ubuntu-latest'
    - name: Test system
      run: |
        set -o errexit
        set -o pipefail
        
        ../fats/install.sh kubebuilder
        ../fats/install.sh kustomize
        make compile test
      working-directory: system
      if: success() && matrix.os == 'ubuntu-latest'
    - name: Report coverage
      run: curl -s https://codecov.io/bash | bash -s
      shell: bash
      env:
        CODECOV_TOKEN: 9ff1715b-5be2-44d7-ae21-b14ff7165fa9
      continue-on-error: true

  stage:
    name: Stage
    if: success() && github.event_name == 'push' && startsWith(github.repository, 'projectriff/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13'
    # TODO remove after https://github.com/actions/setup-go/issues/14
    - name: Add GOPATH/bin to PATH
      run: |
        echo "##[set-env name=GOPATH;]$(go env GOPATH)"
        echo "##[add-path]$(go env GOPATH)/bin"
      shell: bash
    - uses: actions/setup-java@v1
      with:
        java-version: '8.x'
    - name: GCP login
      run: ./fats/install.sh gcloud
      env:
        GCLOUD_CLIENT_SECRET: ${{ secrets.GCLOUD_CLIENT_SECRET }}
    - name: docker login
      run: echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
      shell: bash
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - name: Setup env
      run: |
        readonly version=$(cat VERSION)
        readonly git_sha=$(git rev-parse HEAD)
        readonly git_timestamp=$(TZ=UTC git show --quiet --date='format-local:%Y%m%d%H%M%S' --format="%cd")
        readonly slug=${version}-${git_timestamp}-${git_sha:0:16}
        echo "##[set-env name=VERSION_SLUG]${slug}"
      shell: bash
      
    - name: Stage cli
      run: ../.github/workflows/ci-cli/stage.sh
      working-directory: cli
    - name: Stage dev-utils
      run: ../.github/workflows/ci-dev-utils/stage.sh
      working-directory: dev-utils
    - name: Stage streaming-processor
      run: ../.github/workflows/ci-streaming-processor/stage.sh
      working-directory: streaming-processor
    - name: Stage system
      run: ../.github/workflows/ci-system/stage.sh
      working-directory: system
    - name: Stage release
      run: ../.github/workflows/ci-release/stage.sh
      working-directory: release

  acceptance:
    name: Acceptance
    needs:
    - unit
    - stage
    if: success() && github.event_name == 'push'
    strategy:
      matrix:
        config:
        - qualifier: core
          os: ubuntu-latest
          cluster: kind
          registry: dockerhub
          runtime: core
        - qualifier: knative
          os: ubuntu-latest
          cluster: kind
          registry: dockerhub
          runtime: knative
        - qualifier: streaming-inmemory
          os: ubuntu-latest
          cluster: kind
          registry: dockerhub
          runtime: streaming
          gateway: inmemory
        - qualifier: streaming-kafka
          os: ubuntu-latest
          cluster: kind
          registry: dockerhub
          runtime: streaming
          gateway: kafka
        - qualifier: streaming-pulsar
          os: ubuntu-latest
          cluster: kind
          registry: dockerhub
          runtime: streaming
          gateway: pulsar
      fail-fast: false
    runs-on: ${{ matrix.config.os }}
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GCLOUD_CLIENT_SECRET: ${{ secrets.GCLOUD_CLIENT_SECRET }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup env
      run: |
        job=$(date +%s) # TODO use something that is assigned by CI to guarantee uniqueness
        echo "JOB_ID=${job}"

        echo "##[set-env name=CLUSTER]${{ matrix.config.cluster }}"
        echo "##[set-env name=REGISTRY]${{ matrix.config.registry }}"
        echo "##[set-env name=CLUSTER_NAME]release-${job}-${{ matrix.config.qualifier }}"
        echo "##[set-env name=NAMESPACE]release-${job}-${{ matrix.config.qualifier }}"
        echo "##[set-env name=RUNTIME]${{ matrix.config.runtime }}"
        echo "##[set-env name=GATEWAY]${{ matrix.config.gateway }}"

        readonly version=$(cat VERSION)
        readonly git_sha=$(git rev-parse HEAD)
        readonly git_timestamp=$(TZ=UTC git show --quiet --date='format-local:%Y%m%d%H%M%S' --format="%cd")
        readonly slug=${version}-${git_timestamp}-${git_sha:0:16}
        echo "##[set-env name=VERSION_SLUG]${slug}"
      shell: bash
    - name: Install tools
      run: |
        ../fats/install.sh kubectl
        ../fats/install.sh riff builds/v${VERSION_SLUG}
        ../fats/install.sh helm
        ../fats/install.sh ytt
        ../fats/install.sh kapp
        ../fats/install.sh gcloud
      working-directory: release
      shell: bash
    - name: Start
      run: fats/start.sh
      shell: bash
      timeout-minutes: 15
    - name: Install riff
      run: .github/workflows/install-riff.sh staged
      shell: bash
      timeout-minutes: 15
    - name: Run tests
      run: .github/workflows/acceptance.sh
      shell: bash
      timeout-minutes: 30
    - name: Collect diagnostics
      run: fats/diagnostics.sh
      shell: bash
      if: always()
      timeout-minutes: 1
    - name: Uninstall riff
      run: .github/workflows/cleanup-riff.sh
      shell: bash
      if: always()
      timeout-minutes: 10
    - name: Cleanup
      run: fats/cleanup.sh
      shell: bash
      if: always()
      timeout-minutes: 10

  publish:
    name: Publish
    needs: acceptance
    # TODO(scothis) remove publishing from mono branch
    if: |
      success() && github.event_name == 'push' && startsWith(github.repository, 'projectriff/') && (
        github.ref == 'refs/heads/mono' ||
        github.ref == 'refs/heads/master' || (
          startsWith(github.ref, 'refs/heads/v') && endsWith(github.ref, 'x')
        )
      )
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GCLOUD_CLIENT_SECRET: ${{ secrets.GCLOUD_CLIENT_SECRET }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup env
      run: |
        readonly version=$(cat VERSION)
        readonly git_sha=$(git rev-parse HEAD)
        readonly git_timestamp=$(TZ=UTC git show --quiet --date='format-local:%Y%m%d%H%M%S' --format="%cd")
        readonly slug=${version}-${git_timestamp}-${git_sha:0:16}
        echo "##[set-env name=VERSION]${version}"
        echo "##[set-env name=VERSION_SLUG]${slug}"
      shell: bash
    - name: Install tools
      run: |
        ./fats/install.sh gcloud
      shell: bash

    - name: Publish cli
      run: ../.github/workflows/ci-cli/publish.sh
      working-directory: cli
    - name: Publish dev-utils
      run: ../.github/workflows/ci-dev-utils/publish.sh
      working-directory: dev-utils
    - name: Publish release
      run: ../.github/workflows/ci-release/publish.sh
      working-directory: release
